// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Dots_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector2> PixelSize = ParameterKeys.NewValue<Vector2>(new Vector2(32.0f,32.0f));
        public static readonly ValueParameterKey<bool> Alpha = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<bool> Point = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<float> Smooth = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<Vector2> Scale = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
    }
}
