// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Hatch_Line_TextureFXKeys
    {
        public static readonly ValueParameterKey<Color4> BackgroundColor = ParameterKeys.NewValue<Color4>(new Color4(0.0f,0.0f,0.0f,1.0f));
        public static readonly ValueParameterKey<Color4> HatchColor = ParameterKeys.NewValue<Color4>(new Color4(1.0f,1.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<float> Threshhold = ParameterKeys.NewValue<float>(5.0f);
        public static readonly ValueParameterKey<float> Thickness = ParameterKeys.NewValue<float>(4.0f);
        public static readonly ValueParameterKey<float> Rotation = ParameterKeys.NewValue<float>(0.36f);
    }
}
