// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Mosaic_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector2> Cells = ParameterKeys.NewValue<Vector2>(new Vector2(1,1));
        public static readonly ValueParameterKey<bool> Mirror = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<float> Rotation = ParameterKeys.NewValue<float>(0);
        public static readonly ValueParameterKey<Vector2> Scaling = ParameterKeys.NewValue<Vector2>(new Vector2(1,1));
        public static readonly ValueParameterKey<bool> Stripes = ParameterKeys.NewValue<bool>(false);
    }
}
