// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Scanline_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> Brightness = ParameterKeys.NewValue<float>(1);
        public static readonly ValueParameterKey<Vector2> Amount = ParameterKeys.NewValue<Vector2>(new Vector2(1,1));
        public static readonly ValueParameterKey<Vector2> RedShift = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> GreenShift = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> BlueShift = ParameterKeys.NewValue<Vector2>();
    }
}
