// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace VL.ImGui.Stride.Effects
{
    internal static partial class ImGuiEffectShaderKeys
    {
        public static readonly ValueParameterKey<Matrix> proj = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector2> offset = ParameterKeys.NewValue<Vector2>();
    }
}
