// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace VL.Stride.Rendering
{
    internal static partial class ShaderMixins
    {
        internal partial class VLAtmosphereEffectMain  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "StrideForwardShadingEffect");
                if (context.GetParam(VLEffectParameters.EnableExtensionShader))
                {
                    context.Mixin(mixin, context.GetParam(VLEffectParameters.MaterialExtensionShader));
                }
                if (context.GetParam(VLEffectParameters.EnableExtensionNameMesh))
                {
                    context.Mixin(mixin, context.GetParam(VLEffectParameters.MaterialExtensionNameMesh));
                }
                if (context.GetParam(VLEffectParameters.EnableExtensionShaderMesh))
                {
                    context.Mixin(mixin, context.GetParam(VLEffectParameters.MaterialExtensionShaderMesh));
                }
                if (context.GetParam(AtmosphereForwardShadingEffectParameters.RenderAerialPerspective))
                    context.Mixin(mixin, "AtmosphereForwardRender");
            }

            [System.Runtime.CompilerServices.ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("VLAtmosphereEffectMain", new VLAtmosphereEffectMain());
            }
        }
    }
}
