// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class MapColor_TextureFXKeys
    {
        public static readonly ValueParameterKey<int> Type = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<Vector2> Start = ParameterKeys.NewValue<Vector2>(new Vector2(0.0f,0.0f));
        public static readonly ValueParameterKey<Vector2> End = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
        public static readonly ValueParameterKey<float> MapSmooth = ParameterKeys.NewValue<float>(0.0f);
    }
}
