// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Metallica_TextureFXKeys
    {
        public static readonly ValueParameterKey<Color4> ColorA = ParameterKeys.NewValue<Color4>(new Color4(0.60f,0.99f,0.96f,1.0f));
        public static readonly ValueParameterKey<Color4> ColorB = ParameterKeys.NewValue<Color4>(new Color4(0.57f,0.41f,0.07f,1.0f));
        public static readonly ValueParameterKey<Vector2> Angle = ParameterKeys.NewValue<Vector2>(new Vector2(0.0f,0.0f));
        public static readonly ValueParameterKey<Vector2> BumpAmount = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
        public static readonly ValueParameterKey<Vector2> BumpGamma = ParameterKeys.NewValue<Vector2>(new Vector2(0.0f,0.0f));
        public static readonly ValueParameterKey<Vector2> Brightness = ParameterKeys.NewValue<Vector2>(new Vector2(0.0f,0.0f));
        public static readonly ValueParameterKey<float> Emboss = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> Shape = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> MaxRadius = ParameterKeys.NewValue<float>(1.0f);
    }
}
