// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Quantize_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector4> StepSize = ParameterKeys.NewValue<Vector4>(new Vector4(0.1f,0.1f,0.1f,0.1f));
        public static readonly ValueParameterKey<uint> Mode = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<bool> QuantizeAlpha = ParameterKeys.NewValue<bool>();
    }
}
