// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Sharpen_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> Amount = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> Radius = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> Saturation = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> Gamma = ParameterKeys.NewValue<float>(0.0f);
    }
}
