// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class ShiftRGB_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> Direction = ParameterKeys.NewValue<float>(0.25f);
        public static readonly ValueParameterKey<float> Shift = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> Hue = ParameterKeys.NewValue<float>(0.1f);
    }
}
