// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class ProjectedTexture_DrawFXKeys
    {
        public static readonly ObjectParameterKey<Texture> Source = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> Sampler0 = ParameterKeys.NewObject<SamplerState>();
        public static readonly ValueParameterKey<Matrix> ProjectorViewInverse = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector3> ProjectorPosition = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<Matrix> ProjectorPerspective = ParameterKeys.NewValue<Matrix>();
    }
}
