// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class RaymarcherMatcapKeys
    {
        public static readonly ValueParameterKey<int> marchMaxIterations = ParameterKeys.NewValue<int>(120);
        public static readonly ValueParameterKey<float> marchMaxDistance = ParameterKeys.NewValue<float>(200);
        public static readonly ValueParameterKey<float> marchMinDistance = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> marchStepLength = ParameterKeys.NewValue<float>(0.75f);
        public static readonly ValueParameterKey<float> alpha = ParameterKeys.NewValue<float>(1);
        public static readonly ValueParameterKey<float> aoScale = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> aoBias = ParameterKeys.NewValue<float>(0.5f);
    }
}
