// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Posterize_RGB_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector4> Levels = ParameterKeys.NewValue<Vector4>(new Vector4(4,4,4,4));
        public static readonly ValueParameterKey<bool> Alpha = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<Vector4> Dithering = ParameterKeys.NewValue<Vector4>(new Vector4(0,0,0,0));
        public static readonly ValueParameterKey<float> Smooth = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<Vector4> Phase = ParameterKeys.NewValue<Vector4>(new Vector4(0,0,0,0));
    }
}
