// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Erode_Color_TextureFXKeys
    {
        public static readonly ValueParameterKey<int> Size = ParameterKeys.NewValue<int>(1);
        public static readonly ValueParameterKey<float> Separation = ParameterKeys.NewValue<float>(1);
        public static readonly ValueParameterKey<float> MinThreshold = ParameterKeys.NewValue<float>(0.2f);
        public static readonly ValueParameterKey<float> MaxThreshold = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<uint> Shape = ParameterKeys.NewValue<uint>();
    }
}
