// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class BubbleNoise_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> Time = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Frequency = ParameterKeys.NewValue<float>(3.5f);
        public static readonly ValueParameterKey<float> Contrast = ParameterKeys.NewValue<float>(0.15f);
        public static readonly ValueParameterKey<Color4> BackgroundColor = ParameterKeys.NewValue<Color4>(new Color4(0,0,0,1));
        public static readonly ValueParameterKey<Color4> BubbleColor = ParameterKeys.NewValue<Color4>(new Color4(1,1,1,1));
    }
}
