// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Electricity_Internal_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> Time = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<Texture> NoiseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Color4> BackgroundColor = ParameterKeys.NewValue<Color4>(new Color4(0.0f,0.0f,0.0f,1.0f));
        public static readonly ValueParameterKey<Color4> ElectricityColor = ParameterKeys.NewValue<Color4>(new Color4(1.0f,1.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<float> Height = ParameterKeys.NewValue<float>(0.25f);
        public static readonly ValueParameterKey<float> VertexNoise = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> GlowStrength = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> GlowFallOff = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> AmbientGlow = ParameterKeys.NewValue<float>(0.25f);
        public static readonly ValueParameterKey<float> AmbientGlowHeightScale = ParameterKeys.NewValue<float>(0.5f);
    }
}
