// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Bump_TextureFXKeys
    {
        public static readonly ValueParameterKey<int> Type = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<Vector3> LightDirection = ParameterKeys.NewValue<Vector3>(new Vector3(0.25f,-0.5f,0.1f));
        public static readonly ValueParameterKey<Color4> AmbientColor = ParameterKeys.NewValue<Color4>(new Color4(0.15f,0.15f,0.15f,1.0f));
        public static readonly ValueParameterKey<Color4> DiffuseColor = ParameterKeys.NewValue<Color4>(new Color4(0.85f,0.85f,0.85f,1.0f));
        public static readonly ValueParameterKey<Color4> SpecularColor = ParameterKeys.NewValue<Color4>(new Color4(0.35f,0.35f,0.35f,1.0f));
        public static readonly ValueParameterKey<float> LightPower = ParameterKeys.NewValue<float>(25.0f);
        public static readonly ValueParameterKey<float> LightRange = ParameterKeys.NewValue<float>(10.0f);
        public static readonly ValueParameterKey<float> LightAttenuation0 = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> LightAttenuation1 = ParameterKeys.NewValue<float>(0.3f);
        public static readonly ValueParameterKey<float> LightAttenuation2 = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> SmoothSpot = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> BumpAmount = ParameterKeys.NewValue<float>(1.0f);
    }
}
