// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class CartesianToPolar_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> Interpolation = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> Repeats = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<bool> Clamp = ParameterKeys.NewValue<bool>(true);
        public static readonly ValueParameterKey<float> Scale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> Twirl = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> Squeeze = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> Zoom = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> Lens = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> OffsetX = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> OffsetY = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> TunnelX = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> TunnelY = ParameterKeys.NewValue<float>(0.0f);
    }
}
