// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Displace_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector2> Offset = ParameterKeys.NewValue<Vector2>(new Vector2(0.5f,0.5f));
        public static readonly ValueParameterKey<Vector2> OffsetScale = ParameterKeys.NewValue<Vector2>(new Vector2(0.1f,0.1f));
    }
}
