// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Magnify_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector2> Center = ParameterKeys.NewValue<Vector2>(new Vector2(0.5f,0.5f));
        public static readonly ValueParameterKey<float> InnerRadius = ParameterKeys.NewValue<float>(0.25f);
        public static readonly ValueParameterKey<float> Magnification = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> OuterRadius = ParameterKeys.NewValue<float>(0.5f);
    }
}
