// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Muffy_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> RingAmount = ParameterKeys.NewValue<float>(2.5f);
        public static readonly ValueParameterKey<float> RingSize = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ObjectParameterKey<SamplerState> s0 = ParameterKeys.NewObject<SamplerState>();
    }
}
