// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Undistort_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector2> FocalLength = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PrincipalPoint = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector4> Distortion = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector2> Resolution = ParameterKeys.NewValue<Vector2>();
    }
}
