// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Clamp_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector4> Min = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> Max = ParameterKeys.NewValue<Vector4>(new Vector4(1,1,1,1));
    }
}
