// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class SplitChannels_Internal_ComputeFXKeys
    {
        public static readonly ObjectParameterKey<Texture> Tex = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector2> InputSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ObjectParameterKey<Texture> Channel0 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Channel1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Channel2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Channel3 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> TexSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
