// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Swizzle_TextureFXKeys
    {
        public static readonly ValueParameterKey<int> Channel0 = ParameterKeys.NewValue<int>(0);
        public static readonly ValueParameterKey<int> Channel1 = ParameterKeys.NewValue<int>(1);
        public static readonly ValueParameterKey<int> Channel2 = ParameterKeys.NewValue<int>(2);
        public static readonly ValueParameterKey<int> Channel3 = ParameterKeys.NewValue<int>(3);
    }
}
